# Generated by Django 4.0.4 on 2022-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRecommender',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('movie1', models.IntegerField()),
                ('movie2', models.IntegerField()),
                ('movie3', models.IntegerField()),
                ('movie4', models.IntegerField()),
                ('movie5', models.IntegerField()),
            ],
        ),
    ]
