# Generated by Django 4.0.4 on 2022-06-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_collabarativemovierecommender_movie6'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixMovieRecommender',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('movie1', models.IntegerField()),
                ('movie2', models.IntegerField()),
                ('movie3', models.IntegerField()),
                ('movie4', models.IntegerField()),
                ('movie5', models.IntegerField()),
            ],
        ),
    ]
